# Generated by Django 5.2.5 on 2025-11-10 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='category',
            field=models.CharField(choices=[('license', 'License & Certification'), ('competition', 'Competition & Award')], default='competition', max_length=100),
        ),
    ]
