# Generated by Django 5.2.5 on 2025-11-10 09:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=150)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('focus_area', models.CharField(help_text='e.g., Capital Markets, Leadership', max_length=120)),
                ('quote', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(default=5, help_text='Rating from 1 to 5 stars.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
